package org.ufuk.quantum.resonance.projection.sim;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 * Dimensional Projection Theory of Consciousness - Prototyping Simulation
 * Author: Ufuk Tiryaki
 * Date: May 2026
 * Description: Visualizing how the brain acts as a geometric receiver, translating
 * higher-dimensional quantum resonance patterns into a 3D cognitive state (Intuition/Eureka).
 *
 * Left Side: 3+1D Mechanical Timeline running an ACTUAL Goldbach Conjecture partition algorithm.
 * Since every checked number satisfies the conjecture, the search for a counterexample returns 'FALSE'.
 * Right Side: 4+1D Quantum Resonance Pattern capturing the holistic wave interference of the timeline.
 */
public class QuantumResonanceSimulation extends JPanel implements ActionListener {

    private final Timer timer;
    private double timeStep = 0;
    private final int WIDTH = 1200;
    private final int HEIGHT = 650;

    // List storing 5D points generated by overlapping quantum resonance waves
    private final List<Point5D> resonancePattern = new ArrayList<>();

    // Lists and variables for the Left Panel (Actual Goldbach computation log)
    private final List<String> goldbachComputationLog = new ArrayList<>();
    private long currentEvenNumber = 4;

    public QuantumResonanceSimulation() {
        // Simulation loop running at ~50 FPS (20ms refresh rate)
        timer = new Timer(20, this);
        timer.start();

        JFrame frame = new JFrame("Quantum Resonance & Dimensional Projection Theory");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(WIDTH, HEIGHT);
        frame.add(this);
        frame.setVisible(true);
    }

    // --- INTEGRATED MATHEMATICAL GOLDBACH ENGINE ---

    private boolean isPrime(int n) {
        if (n <= 1) return false;
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) return false;
        }
        return true;
    }

    private String findGoldbachPartition(long n) {
        for (int i = 2; i <= n / 2; i++) {
            if (isPrime(i) && isPrime((int)(n - i))) {
                return n + " = " + i + " + " + (n - i);
            }
        }
        return ""; // Returns empty if a counterexample is found (Conjecture fails)
    }

    // ------------------------------------------------

    // Class representing the 5-Dimensional Quantum State
    static class Point5D {
        double x, y, z, t, w;
        Color color;

        Point5D(double x, double y, double z, double t, double w, Color color) {
            this.x = x; // Spectral X
            this.y = y; // Spectral Y
            this.z = z; // 3D Spatial Depth
            this.t = t; // Timeline position (Linear time)
            this.w = w; // 5th Dimension (Quantum Resonance Amplitude)
            this.color = color;
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Cosmic Texture Background
        g2d.setColor(new Color(6, 6, 18));
        g2d.fillRect(0, 0, WIDTH, HEIGHT);

        // Screen Divider
        g2d.setColor(new Color(30, 30, 50));
        g2d.drawLine(WIDTH / 2, 0, WIDTH / 2, HEIGHT);

        // Section Headers
        g2d.setFont(new Font("Arial", Font.BOLD, 14));
        g2d.setColor(Color.RED);
        g2d.drawString("3+1D CLASSIC TIMELINE (Goldbach Real-Time Computation / Turing)", 30, 40);
        g2d.setColor(Color.CYAN);
        g2d.drawString("4+1D RESONANCE PATTERN (The Holographic Totality Sensed by Mind)", WIDTH / 2 + 30, 40);

        // ----------------- LEFT SIDE: MATHEMATICAL LOG & TIMELINE -----------------
        g2d.setFont(new Font("Monospaced", Font.PLAIN, 12));
        g2d.setColor(Color.GRAY);
        g2d.drawString("Searching for a counterexample:", 30, 65);

        // Render the actual step-by-step mathematical log of Goldbach testing
        g2d.setFont(new Font("Monospaced", Font.PLAIN, 12));
        int logYOffset = 95;
        synchronized (goldbachComputationLog) {
            int startIdx = Math.max(0, goldbachComputationLog.size() - 18);
            for (int i = startIdx; i < goldbachComputationLog.size(); i++) {
                String logLine = goldbachComputationLog.get(i);

                // Splitting and highlighting the FALSE condition of the counterexample search
                if (logLine.contains("FALSE")) {
                    g2d.setColor(Color.LIGHT_GRAY);
                    g2d.drawString(logLine.substring(0, logLine.indexOf("FALSE")), 40, logYOffset);
                    g2d.setColor(Color.RED);
                    g2d.drawString("FALSE (Keep Searching...)", 40 + g2d.getFontMetrics().stringWidth(logLine.substring(0, logLine.indexOf("FALSE"))), logYOffset);
                } else {
                    g2d.setColor(Color.LIGHT_GRAY);
                    g2d.drawString(logLine, 40, logYOffset);
                }
                logYOffset += 20;
            }
        }

        g2d.setFont(new Font("Arial", Font.ITALIC, 13));
        g2d.setColor(Color.LIGHT_GRAY);
        g2d.drawString("Mechanical State: Loop active. Verifying numbers one by one to infinity.", 30, HEIGHT - 50);


        // ----------------- RIGHT SIDE: HOLISTIC GEOMETRIC PATTERN -----------------
        g2d.setFont(new Font("Arial", Font.PLAIN, 12));
        g2d.setColor(Color.WHITE);
        g2d.drawString("The brain reads the lower-dimensional shadow of this quantum attractor as 'INTUITION'.", WIDTH / 2 + 30, 65);

        int rightCenterX = (3 * WIDTH) / 4;
        int rightCenterY = HEIGHT / 2;

        // Projecting 5D Resonance Points onto the 2D Screen
        synchronized (resonancePattern) {
            for (Point5D p : resonancePattern) {
                double scale = 1.0 / (1.0 + p.z * 0.002); // 3D depth illusion

                // The 5th-dimensional resonance (p.w) creates a non-linear geometric pattern in the projection
                int screenX = rightCenterX + (int) ((p.x * Math.cos(p.t * 0.02) + p.w * Math.sin(p.w * 0.1)) * scale);
                int screenY = rightCenterY + (int) ((p.y * Math.sin(p.t * 0.02) + p.w * Math.cos(p.t * 0.01)) * scale);

                // Time-decay wave transparency effect
                int alpha = Math.max(10, (int) (p.w * 3) % 255);
                g2d.setColor(new Color(p.color.getRed(), p.color.getGreen(), p.color.getBlue(), alpha));

                // Rendering the non-linear dots forming the cognitive attractor
                g2d.fillOval(screenX, screenY, 3, 3);
            }
        }

        // Cognitive State / Projection Output
        g2d.setFont(new Font("Arial", Font.ITALIC, 13));
        g2d.setColor(Color.LIGHT_GRAY);
        g2d.drawString("Cognitive State: Pattern Created!", WIDTH / 2 + 30, HEIGHT - 50);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        timeStep += 0.1;

        // --- Left Panel Engine Action ---
        // Run your actual Goldbach partition algorithm
        String partitionResult = findGoldbachPartition(currentEvenNumber);
        String stepLog;

        if (!partitionResult.isEmpty()) {
            // A partition exists, meaning this number is NOT a counterexample.
            // Therefore, the condition "Did we find a counterexample to break the conjecture?" is FALSE.
            stepLog = "[t=" + String.format("%.1f", timeStep) + "] Checked N=" + currentEvenNumber + " (" + partitionResult + ") -> Found? FALSE";
        } else {
            // Theoretically, if it returns empty, Goldbach has failed (Historical Discovery!)
            stepLog = "[t=" + String.format("%.1f", timeStep) + "] Checked N=" + currentEvenNumber + " -> COUNTEREXAMPLE FOUND! HALT.";
        }

        synchronized (goldbachComputationLog) {
            goldbachComputationLog.add(stepLog);
            if (goldbachComputationLog.size() > 50) {
                goldbachComputationLog.removeFirst();
            }
        }

        // --- Right Panel Manifold Generation ---
        // We take the timeline values and current computed values to construct the 5D quantum geometry
        double theta = timeStep * 0.5;

        // Use the actual processed even number to modulate the 5th-dimensional resonance (w)
        double wResonance = 40 + 60 * Math.sin(currentEvenNumber * 0.05) * Math.cos(currentEvenNumber * 0.01);

        // Map the metrics into a non-linear space attractor configuration
        double nextX = 140 * Math.sin(theta * 1.2) * Math.cos(wResonance * 0.02);
        double nextY = 140 * Math.cos(theta * 0.9) * Math.sin(wResonance * 0.03);
        double nextZ = 100 * Math.sin(wResonance);

        // Dynamic color shifting based on the progress of the actual checked number
        int r = (int) (127 + 127 * Math.sin(currentEvenNumber * 0.01));
        int g = (int) (127 + 127 * Math.cos(currentEvenNumber * 0.02));
        int b = 255;
        Color waveColor = new Color(r, g, b);

        synchronized (resonancePattern) {
            resonancePattern.add(new Point5D(nextX, nextY, nextZ, timeStep, wResonance, waveColor));
            if (resonancePattern.size() > 18000) {
                resonancePattern.removeFirst();
            }
        }

        // Advance to the next even number for the next simulation frame
        currentEvenNumber += 2;

        repaint(); // Trigger UI paint update
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(QuantumResonanceSimulation::new);
    }
}